class worfklow_dict:
    def __init__(self):
        self.help_general = {
            "input": "In case of vcf, the input file must end with .csv and in case of plink, it must end with .p.csv.(see ./example_files/example_vcf_input.csv)",
            "outDir ": "Path to the directory, where all the outputs will be stored. If the directory is not present, it will be created.",
            "sample_map": "Path to the sample map file(must end with .map).Format:first column as sample id and second column as population id.Required only if the input is vcf.",
            "color_map": "Path to the file containing population name as first column and color in hex codes as second column.Must end with .map",
            "outprefix": "prefix of the outputs generated by the workflow",
            "max_chrom": "Maximum number of chromosomes to be considered for the analyses, note that the workflow deals only with the autosomal chromosomes.",
            "allow_extra_chrom": "set this argument to true if the chromosome id contains a string, default: false",
            "chrom_length_map": "If the inputs are plink binary files, map file is needed to set the chromosome id and its respective size in the vcf header, If not provided, the greatest coordinate for each chromosome will be considered as its total size. The file must end with .map.",
            "fasta": "If the inputs are plink binary files, fasta file is needed to set the reference allele in the converted vcf files. If not provided, the major allele will be set as the reference allele for all positions for all analyses",
            "outgroup": "The population id to be used as an outgroup in the following analyses: 1). treemix --> as a root in ML phylogenetic tree, 2). Fst- and IBS-based NJ clustering --> as a root, 3). signature of selection --> to determine the ancestral and derived alleles",
        }

        self.param_general = {
            "input": "null",
            "outDir": "scalepopgn",
            "sample_map": "null",
            "color_map": "null",
            "outprefix": "scalepopgen",
            "max_chrom": 29,
            "allow_extra_chrom": False,
            "chrom_length_map": "null",
            "fasta": "null",
            "outgroup": "null",
        }

        self.help_indi_filtering = {
            "apply_indi_filters": "Perform sample filtering?",
            "king_cutoff": "Threshold of relatedness to remove samples",
            "mind": "Threshold of missing genotypes to remove samples",
            "rem_indi": "Remove custom samples",
        }

        self.param_indi_filtering = {
            "apply_indi_filters": False,
            "king_cutoff": 0.0884,
            "mind": 0.05,
            "rem_indi": "null",
        }

        self.help_snp_filtering = {
            "apply_snp_filters": "Perform site filtering?",
            "rem_snps": "Remove custom sites",
            "maf": "Threshold of minor allele frequency to remove sites",
            "min_meanDP": "Lower threshold of average depth to remove sites",
            "max_meanDP": "Upper threshold of average depth to remove sites",
            "hwe": "Threshold of HWE p-value to remove sites",
            "max_missing": "Threshold of missing genotypes to remove sites",
            "minQ": "Threshold of quality to remove sites",
            "indiv_summary": "Calculate sample-based summary statistics?",
        }

        self.param_snp_filtering = {
            "apply_snp_filters": False,
            "rem_snps": "null",
            "maf": 0.05,
            "min_meanDP": "null",
            "max_meanDP": "null",
            "hwe": "null",
            "max_missing": 0.05,
            "minQ": "null",
        }

        self.help_genetic_structure = {
            "genetic_structure": "Perform analyses of genetic structure? Setting this to false, will skip all the analyses mentioned below",
            "rem_indi_structure": "Remove custom samples",
            "ld_filt": "Filter sites based on linkage disequilibrium using plink2? Setting this to False, will skip the step of LD filtering",
            "ld_window_size": "Window size for LD filtering",
            "ld_step_size": "Step size for LD filtering",
            "r2_threshold": "Threshold of r2 for LD filtering",
            "smartpca": "Perform principal component analysis?",
            "smartpca_param": "Additional parameters for PCA",
            "pca_plot_yml": "The yml file to plot interactive PCA results",
            "marker_map": "Marker shapes for PCA plot",
            "chrom_map": "Map file to replace chromosome ids (see ./example_files/oldchrom_newchrom.map",
            "admixture": "Perform analysis with Admixture?",
            "start_k": "Starting K-value for Admixture",
            "end_k": "Ending K-value for Admixture",
            "admixture_args": "Set additional parameters of ADMIXTURE tools",
            "admixture_colors": "Custom colors for Admixture plot",
            "admixture_plot_pop_order": "Order of populations for Admixture plot",
            "admixture_plot_yml": "The yml file to plot interactive Admixture results",
            "pairwise_global_fst": "Calculate pairwise Fst distances?",
            "fst_plot_yml": "The yml file to plot interactive Fst-based NJ tree",
            "ibs_dist": "Calculate 1-ibs distances?",
            "ibs_plot_yml": "The yml file to plot interactive IBS-based NJ tree",
        }

        self.param_genetic_structure = {
            "genetic_structure": False,
            "rem_indi_structure": "null",
            "ld_filt": False,
            "ld_window_size": 50,
            "ld_step_size": 10,
            "r2_threshold": 0.1,
            "smartpca": False,
            "smartpca_param": "null",
            "pca_plot_yml": "popgen48-scalepopgen/extra/plots/pca.yml",
            "marker_map": "null",
            "chrom_map": "null",
            "admixture": False,
            "start_k": 2,
            "end_k": 21,
            "admixture_args": "--cv=5",
            "admixture_colors": "popgen48-scalepopgen/extra/hexcolorcodes.txt",
            "admixture_plot_pop_order": "null",
            "admixture_plot_yml": "popgen48-scalepopgen/extra/plots/admixture.yml",
            "pairwise_global_fst": False,
            "fst_plot_yml": "popgen48-scalepopgen/extra/plots/fst_nj.yml",
            "ibs_dist": False,
            "ibs_plot_yml": "popgen48-scalepopgen/extra/plots/ibs_nj.yml",
        }

        self.help_treemix = {
            "treemix": "whether to run the treemix workflow",
            "k_snps": "windows of size n SNPs to be grouped together for treemix analysis",
            "treemix_args": "Set additional parameters of treemix tools",
            "n_bootstrap": "number of bootstrapping to run for treemix analyis (without migration edge)",
            "set_random_seed": "whether to set the seed for random number generation",
            "n_mig": "total number of migration edges to be added, set this to zero to skip adding migration edges",
            "n_iter": "number of iterations to be carried out for each migration edge value",
            "rand_k_snps": "whether or not to randomized the values of k_snps for each iteration of n_iter",
        }

        self.param_treemix = {
            "treemix": False,
            "k_snps": 500,
            "treemix_args": "null",
            "n_bootstrap": 5,
            "set_random_seed": True,
            "n_mig": 4,
            "n_iter": 3,
            "rand_k_snps": True,
        }

        self.selection_options = {
            "min_sample_size": 8,
            "skip_pop": "null",
            "skip_outgroup": "false",
            "selection_plot_yml": "popgen48-scalepopgen/extra/plots/manhattanplot.yml",
            "pairwise_local_fst": "true",
            "fst_one_vs_all": "true",
            "tajimas_d": "true",
            "pi_val": "true",
            "skip_chromwise": "false",
            "window_size": 50000,
            "step_size": 50000,
            "perc_threshold": 0.01,
        }
        self.tool_args = {
            "admixture_args": [
                "--seed",
                "-m",
                "--method",
                "-a",
                "--acceleration",
                "-C",
                "-c",
                "-B",
                "--cv",
            ],
            "treemix_args": [
                "-noss",
                "-cor_mig",
                "-se",
            ],
        }
